# Accents marker used within this sandhi engine.
# Below, we sequentially specify accents defined in https://en.wikipedia.org/wiki/Devanagari_Extended, https://en.wikipedia.org/wiki/Vedic_Extensions and https://en.wikipedia.org/wiki/Devanagari_(Unicode_block). U+A8E0-U+A8F1 U+1CD0-U+1CE8 U+0951-U+0952
[ACCENTS] 
ALL = "꣠--꣱᳐-᳨॒॑ʸ"
YAN = "ʸ"
SANNATARA = "꣣"
SVARITA = "\꣢᳡"
UDATTA = "\꣡"

# OTHER_MARKERS indicate special conditions associated with the preceeding sound, such as padAnta.
[OTHER_MARKERS]
PADAANTA = "ᵖ"


[PRATYAHARA]
ACH = "अआइईउऊऋॠऌॡएऐओऔ"