id = "e-o__a"

priority = -61109

input_pattern = "([एओ])([३ँ]+)([#ACCENTS.ALL]?)([#OTHER_MARKERS.ALL]*)([अ])([३ँ]+)([#ACCENTS.ALL]?)([#OTHER_MARKERS.ALL]*)"
# Note that the pattern above defines: 4 groups for the first vowel, 4 for the second.

[[substitutions]]

pattern = "$1$2$6$3$7$4$8ऽ"
# Above, $2$6 Represents the anunAsikatva-s of the two vowels. $3$7 represents the accents of the two vowels. $4$8 represents the other markings associated with the condition of the two vowels.

[[substitutions.rule_sequence]]
index = "6.1.109"
text = "एङः पदान्तादति"
