id = "iko_yaN_achi__u"

input_pattern = "([उऊ])(ँ?)([ACCENTS]?)([OTHER_MARKERS.ALL]*)([PRATYAHARA.ACH])(ँ?)([ACCENTS]?)([OTHER_MARKERS.ALL]*)"

[[substitutions]]
pattern = "व्$4$2$5$3$6"

[substitutions.rule_sequence]
index_list = ["6.1.77"]
text_list = ["इको यण् अचि"]
examples = ["मधु + अत्र = मध्वत्र"]