id = "iko_yaN_achi__u"

[input]
expression = "([उऊ])(ँ?)([ACCENTS]?)([OTHER_MARKERS.ALL]*)([PRATYAHARA.ACH])(ँ?)([ACCENTS]?)([OTHER_MARKERS.ALL]*)"

[result]
substitutions = ["व्$4$2$5$3$6"]

[suutra]
index = "6.1.77"
text = "इको यण् अचि"
examples = ["मधु + अत्र = मध्वत्र"]