
id = "iko_yaN_achi__i_u-s"

# The below tells the following in a machine-understandable way: Look for patterns where an udAtta or svarita इ or ई (possibly annotated by anunAsika and other markers) is followed by unaccented अच् (also possibly annotated by anunAsika, accent and other markers).
input_pattern = "([इई])(ँ?)([\꣡\꣢᳡]?)([OTHER_MARKERS.ALL]*)([PRATYAHARA.ACH])(ँ?)([OTHER_MARKERS.ALL]*)"
# Note that the pattern above defines: 4 groups for the first vowel, 3 for the second.

[[substitutions]]

pattern = "य्$5$2$6\॑$4$7"
# Above, $5 represents the second vowel being combined. $2$6 Represents the anunAsikatva-s of the two vowels. $4$7 represents the other markings associated with the condition of the two vowels.

[substitutions.rule_sequence]
index_list = ["6.1.77", "8.2.4"]
text_list = ["इको यण् अचि", "उदात्तस्वरितयोर्यणः स्वरितोऽनुदात्तस्य"]
examples = ["दधि + अत्र = दध्यत्र"]