id = "u_non-u-s__ach"

input_pattern = "([उऊ])(ँ?)([^\꣡\꣢᳡]?)([OTHER_MARKERS.ALL]*)([PRATYAHARA.ACH])(ँ?)([ACCENTS]?)([OTHER_MARKERS.ALL]*)"

[[substitutions]]
pattern = "व्$5$2$6$3$7$4$8"
# Above, $5 represents the second vowel being combined. $2$6 Represents the anunAsikatva-s of the two vowels. $3$7 represents the accents of the two vowels. $4$8 represents the other markings associated with the condition of the two vowels.

[substitutions.rule_sequence]
index_list = ["6.1.77"]
text_list = ["इको यण् अचि"]
examples = ["मधु + अत्र = मध्वत्र"]