id = "R-RR_end__R-RR"

priority = -61100.5

input_pattern = "([ऋॠ])([३ँ]*)([#ACCENTS.ALL]?)([#OTHER_MARKERS.ALL]*#OTHER_MARKERS.PADAANTA[#OTHER_MARKERS.ALL]*)([ऋॠ])([३ँ]*)([#ACCENTS.ALL]?)([#OTHER_MARKERS.ALL]*)"
# Note that the pattern above defines: 4 groups for the first vowel, 4 for the second.

[[substitutions]]

pattern = "ॠ$2$6$3$7$4$8"
# Above, $2$6 Represents the anunAsikatva-s of the two vowels. $3$7 represents the accents of the two vowels. $4$8 represents the other markings associated with the condition of the two vowels.

[[substitutions.rule_sequence]]
index = "6.1.101"
text = "अकः सवर्णे दीर्घः"

[[substitutions]]
# An alternate substitution
pattern = "ऋ$2$3#NO_MORE_SANDHI$4$5$6$7$8"
# Above, $5 represents the second vowel being combined. $2$3$4 represent the attributes of the first vowel. $6$7$8 represent the attributes of the second.

[[substitutions.rule_sequence]]
index = "6.1.127"
text = "ऋत्यकः"