id = "yaN-u-s__a"

priority = 1


input_pattern = "(#ACCENT.YAN[#ACCENT.UDATTA#ACCENT.SVARITA])([#ACCENT.SVARITA#ACCENT.SANNATARA]?)"

[[substitutions]]

pattern = "\꣢"

[substitutions.rule_sequence]
index_list = ["8.2.4"]
text_list = ["उदात्तस्वरितयोर्यणः स्वरितोऽनुदात्तस्य"]
examples = []